### PR TITLE
Events triggered on HTML elements should bubble.

### PR DESCRIPTION
**Pull request by mwistrand**
This allows events registered to container nodes to bubble up when triggered on child nodes.

### CODE REVIEW

**Comment by mwistrand** [comment]
We had discussed maintaining an internal queue of events, but then we would also need to implement a way to remove listeners from template nodes on the fly. What's the major benefit to an internal event store over delegating this functionality to the browser?

**Comment by csnover** [comment]
> but what is the major benefit to an internal event store over delegating this functionality to the browser?

How would you delegate event handling to the browser in this case? It doesn’t know or understand our view tree.

**Comment by csnover** [comment]
I’ve landed this code, minus the `removeEventListener` API which shouldn’t be there (that’s not how the Mayhem API works) plus a couple of minor stylistic tweaks, in 6028897ca055a152742626a0b87f2274b155066e.

**Comment by mwistrand** [comment]
Thanks, Colin! I keep forgetting that Mayhem emits its own event objects, making the internal store necessary. Although I'm still curious to know how we might remove listeners from nodes if we need to.

**Comment by csnover** [comment]
> I'm still curious to know how we might remove listeners from nodes if we need to.

It’s not possible since listeners are always removed using the object returned by the call to add them, which is inaccessible to a declaratively created event listener.

**Comment by mwistrand** [comment]
Gotcha. Thanks for the explanation!

**Pull request closed without merging**
